id: AA6E5DAE7
title: Prayer for the Swift Rebirth of Jamyang Khyentse Wangpo
type: translation
pechas:
- I9D008D84
- I7D0AEDDD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:07.115247
  last_modified_at: 2023-01-04 12:02:07.115272
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I9D008D84/B93D: '2883'
  I7D0AEDDD/B60E: '2883'
